### ISSUE TITLE
无法处理番剧文件夹

### ISSUE THREAD

**Issue by nkh0472** [tianyalu/bilibiliVideoConverter#1]
尝试多个番剧均无法转换，仅在输出文件夹中生成提示err_log.txt，提示类似于：
`274 ERROR: 第1个文件的子目录非标准目录：X:\1\s_969\247538`

此处提供示例文件\s_969\247538\entry.json
[entry.json](https://github.com/tianyalu/bilibiliVideoConverter/files/15212626/entry.json)

**Comment by tianyalu** [comment]
最新的代码已支持番剧，请查看README文件
